export { Board, PieceAllegiance } from './chess/board'
export { allegianceSide } from './lib/allegiance'
export { coordinatesEqual } from './lib/coordinate'
export { fileToLetter } from './lib/notation'
export { getCoordsForIndex } from './lib/board'

export type { MoveNode } from './notation/parser'
export type { BoardSquare } from './chess/board-memory'
export type { Coordinates } from './notation/parser'
export type { Piece, Rank, File } from './notation/declarations'
